services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "8000:80"
    depends_on:
      - authentication
      - students
  authentication:
    build:
      context: ./services/authentication
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8001:80"
    networks:
      - backend_network
  students:
    build:
      context: ./services/students
      dockerfile: Dockerfile
    container_name: students_service
    ports:
      - "8002:80"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
